### PR TITLE
- added preview_video_url

### PR DESCRIPTION
**Pull request by Brook-sys**
added preview_video_url

### CODE REVIEW

**Comment by EchterAlsFake** [comment]
Hi, so I tried out the pull request. 
In line: `base_url = re.sub(r'/thumbs(169)?(xnxx)?(l*|poster)/', '/videopreview/', thumb[:self.url.rfind("/")])`

The word `url` is not defined anywhere. I guess you mean `self.url` (So the video URL)?
So I replaced with self.url but I got this URL:

`https://cdn77-pic.xvideos-cdn.com/videos_169.mp4`

With this source URL: `https://de.xvideos.com/video.uaokavf59f0/fremder_lasst_mich_direkt_nach_dem_date_in_frankreich_ihr_croissant_probieren_und_sperma_schlucken_pov`

Is it supposed to be a .mp4 URL? and if I wanted to open it in my browser I got a `403` forbidden error. Maybe I am doing something wrong, please let me know.

But thanks for your pull request. Seems like we are very close :D

**Comment by Brook-sys** [comment]
Hi, sorry for the pull request with errors, I was so anxious to launch it, as it was my first pull request ^^, and regarding the self.url question, it is actually the link to the image thumb .jpg, when I went to edit the code to put it in the repository, I forgot to adapt all the snippets and I forgot even more to test it, anyway I hope everything works out, we are getting there :)

**Comment by EchterAlsFake** [comment]
So, could you please do a second commit with the corrections?

And don't worry, when I did my first Pull request a year ago my hands were shaking like you can't even imagine xD

I am not sure how it works, but I think if you do a second commit to your fork then it should be automatically merged into this Pull Request :)

**Comment by Brook-sys** [comment]
Hello, ok I'll make the corrections and try to send it again, this time it will work :D

**Comment by Brook-sys** [comment]
Hello again, I made the changes and this time I remembered to test before sending, everything worked normally here, I hope everything goes well ;D

**Comment by EchterAlsFake** [comment]
Thank you very much and congratulations to your first pull request! 

:partying_face:

**Pull request merged**
